name = "lilia"
main = "./src/server.js"
compatibility_date="2022-02-26"

account_id = "3ed51f2c99510cd7fe8fcd8ed0621a37"
workers_dev = true

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[env.dev]

[env.production]

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# DISCORD_TEST_GUILD_ID
